### PR TITLE
When retrieving the users in a group we're only interested in their username

### PR DESCRIPTION
**Pull request by pypingou**
Otherwise this fails down the path.

### CODE REVIEW

**Comment by pypingou** [comment]
This fixes a stacktrace received by email and has been hotfixed in prod.

**Comment by puiterwijk** [comment]
:shipit:

**Comment by pypingou** [comment]
Thanks :)

**Comment by pypingou** [comment]
Ok the tests are failing but afaics it's un-related with the present changes, so I'm going to merge them as is.

Thanks again for the review @puiterwijk

**Pull request merged**
