### PR TITLE
Update taskotron tasks namespace

### PR DESCRIPTION
**Pull request by mkrizek**
This is related to #77, since then we decided to change the namespace from 'qa' to 'dist'.

cc'ing @tflink and @kparal

### CODE REVIEW

**Comment by kparal** [comment]
:+1:

**Comment by pypingou** [comment]
I'm suddenly wondering (also for #77) do we have/want to keep some sort of backward compatibility here?

**Comment by kparal** [comment]
Since we changed it quite recently to `qa.*` and nothing broke (Bodhi doesn't seem to rely on exact names), I think we don't need to worry about that too much.

**Comment by pypingou** [comment]
Well, is FMN still working? :)

**Comment by kparal** [comment]
I assume most people use the default filter that we created for them. As long as the default filter is updated with this change, it should be fine, wdyt? We can write a blogpost announcing the changes for the few people who use custom filters.

**Comment by pypingou** [comment]
> I assume most people use the default filter that we created for them. As long as the default filter is updated with this change, it should be fine, wdyt?

I agree, but does that mean that currently it is still working? (Since the changed has already happened and this PR hasn't been released)

> We can write a blogpost announcing the changes for the few people who use custom filters.

Always a good idea :)

Note that if the changed already happen it does not change anything to this PR, my thoughts were more considering a coming change.

**Comment by mkrizek** [comment]
> I agree, but does that mean that currently it is still working? (Since the changed has already happened and this PR hasn't been released)

It's not working atm because we rely on the exact names in the default rules, and the names has changed, if that was what you were asking.

>> We can write a blogpost announcing the changes for the few people who use custom filters.

> Always a good idea :)

I'll write a blogpost about this change (and announce new checks that Taskotron runs) once this is deployed :)

**Comment by sayanchowdhury** [comment]
:+1: for me

**Pull request merged**
